"""update to models to reflect erd

Revision ID: 1839c7e38f81
Revises: 5c331302e401
Create Date: 2024-03-01 15:00:42.529251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1839c7e38f81'
down_revision = '5c331302e401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_message_conversation', 'conversation', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_conversation', type_='foreignkey')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('message_number')

    # ### end Alembic commands ###
