"""Added audio file path to conversation and message objects

Revision ID: 477e6f19be76
Revises: 3758fc21aaf7
Create Date: 2024-04-02 20:39:30.037971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477e6f19be76'
down_revision = '3758fc21aaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_audio_path', sa.String(length=100), nullable=False))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_audio_path', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('tts_audio_path')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('tts_audio_path')

    # ### end Alembic commands ###
